# Key Vault for lab01 secrets. Nobody types the DB password: Terraform generates it,
# stores it here, and the VM reads it with its own managed identity (no keys, no files).

# DATA SOURCE: reads facts about whoever is running Terraform (you, via `az login`).
# Creates nothing. Gives us your tenant_id and object_id.
data "azurerm_client_config" "current" {}

# Key Vault names are GLOBALLY unique across all of Azure (they become <name>.vault.azure.net),
# so we add a random suffix. It is generated once and then remembered in state.
resource "random_string" "kv_suffix" {
  length  = 6
  special = false
  upper   = false
}

resource "azurerm_key_vault" "kv" {
  name                = "kv-lab01-${random_string.kv_suffix.result}"
  location            = azurerm_resource_group.rglab01.location
  resource_group_name = azurerm_resource_group.rglab01.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"

  # Use Azure RBAC (role assignments) for access to secrets, not the older "access policies".
  rbac_authorization_enabled = true

  # Deleted vaults are kept 7 days (the minimum) so they can be recovered.
  # Purge protection OFF so `terraform destroy` can fully remove it in a lab. In prod: true.
  soft_delete_retention_days = 7
  purge_protection_enabled   = false

  tags = local.tags
}

# Being subscription Owner lets you MANAGE the vault (control plane) but NOT read/write the
# secrets inside it (data plane). This role gives data-plane rights to WHOEVER RUNS TERRAFORM,
# so it can write the secret. Terraform is applied by CI only, so this is the CI identity.
resource "azurerm_role_assignment" "me_secrets" {
  scope                = azurerm_key_vault.kv.id
  role_definition_name = "Key Vault Secrets Officer"
  principal_id         = data.azurerm_client_config.current.object_id
}

# A FIXED human admin (you), so you can still read secrets when debugging,
# no matter who ran Terraform. Comes from the GitHub variable ADMIN_OBJECT_ID.
resource "azurerm_role_assignment" "admin_secrets" {
  scope                = azurerm_key_vault.kv.id
  role_definition_name = "Key Vault Secrets Officer"
  principal_id         = var.admin_object_id
}

# A new role assignment takes 1-5 minutes to reach Key Vault (RBAC propagation).
# Without this pause, a fresh apply in CI fails writing the secret with 403 Forbidden.
resource "time_sleep" "wait_for_rbac" {
  create_duration = "120s"
  depends_on      = [azurerm_role_assignment.me_secrets]
}

# A USER-ASSIGNED managed identity: an Azure identity for the VM, created as its own resource.
# Because it exists BEFORE the VM uses it, its role can be granted up front, and it survives
# if the VM is ever replaced (a system-assigned identity would be deleted and recreated with the VM).
resource "azurerm_user_assigned_identity" "vm" {
  name                = "id-lab01-vm"
  location            = azurerm_resource_group.rglab01.location
  resource_group_name = azurerm_resource_group.rglab01.name
  tags                = local.tags
}

# The VM's identity may only READ secrets (least privilege).
resource "azurerm_role_assignment" "vm_secrets" {
  scope                = azurerm_key_vault.kv.id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_user_assigned_identity.vm.principal_id
}

# The DB password, generated by Terraform. special = false keeps it safe inside DATABASE_URL.
resource "random_password" "postgres" {
  length  = 24
  special = false
}

resource "azurerm_key_vault_secret" "postgres" {
  name         = "postgres-password"
  value        = random_password.postgres.result
  key_vault_id = azurerm_key_vault.kv.id

  # Terraform can't see that writing a secret needs MY role first, so we say it explicitly.
  depends_on = [time_sleep.wait_for_rbac]
}
